config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end
  # root to:'_restaurants#index'

  # resources :restaurant

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
    validates :name, uniqueness: true, presence: true
    validates :address, presence: true
    validates :category, inclusion: ["chinese", "italian", "japanese", "french", "belgian"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: {only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
   before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def edit
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    # define the new review
    @review = Review.new(review_params)
    # assign the restaurant
    @review.restaurant = @restaurant
    # save it
    if @review.save
      # redirect_to restaurant_show
      redirect_to @review.restaurant # makes a new request to the server
      # redirect_to restaurant_path(@review.restaurant)
    else
      render :new # gets the file and renders it with the new info
    end
  end

  private
   def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    # filters the user input to use only the correct ones
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar-wagon">
    </div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurant#edit</h1>
<p>Find me in app/views/restaurant/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.category %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Show', restaurant %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/restaurants/show.html.erb
<%= link_to "Back to restaurants", restaurants_path %>

<h2><%= @restaurant.name %></h2>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

  <strong>Category:</strong>
  <%= @restaurant.category.capitalize %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone_number %>
</p>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
<br><br>

<p>
  <strong>Reviews:</strong>
  <br>

   <% @restaurant.reviews.each do |review| %>
   <%= "Rating #{review.rating}"%> <%= "Review: #{review.content}" %> <br>
   <% end %>

</p>

app/views/reviews/new.html.erb
<h1>Create review for <%= @restaurant.name %></h1>


<%= simple_form_for [@restaurant, @review] do |f| %>

  <%= f.input :content, label: "Write a review:" %>

  <%= f.input :rating, label: "Enter a rating from 1 to 5" %>
  <%= f.submit %>
<% end %>